/**
 * Global Mocha/Chai test setup file
 * Provides common utilities and configurations for tests
 */

const { expect } = require('chai');

// Export chai expect for use in tests
module.exports = {
  expect,
  
  // Test constants
  TEST_ADDRESS: "0xb0573e14D92755DE30281f7b10d0F3a5DD3e747B",
  API_KEY: 'DEMO_KEY',

  // Common mocks used across tests
  mocks: {
    emblemopen_create_template: {
      "fromAddress": { "type": "user-provided" },
      "toAddress": { "type": "user-provided" },
      "chainId": { "type": "user-provided" },
      "experimental": true,
      "targetContract": {
        "1": "0x184ddb67E2EF517f6754F055b56905f2A9b29b6A",
        "900": "5rxENZEa3rhDk2hcuG6RNFbCGGQwU9APm4CMmaW4s4xy",
        "name": "EmblemOpen",
        "description": "The vaults within this collection feature deposit addresses spanning two or more blockchains. Vault images, titles, and descriptions are generated by users. Prior to making a purchase, it is advisable to authenticate the legitimacy of the assets within the vault. Supported blockchains encompass, but are not restricted to: Bitcoin, Litecoin, Bitcoin Cash, Ethereum, Dogecoin, Solana, Tezos, Namecoin, and any EVM-compatible protocol.",
        "fusion": false
      },
      "targetAsset": {
        "name": { "type": "user-provided" },
        "image": { "type": "user-provided" },
        "description": { "type": "user-provided" }
      }
    },
    empty_create_template: { 
      "fromAddress": { "type": "user-provided" }, 
      "toAddress": { "type": "user-provided" }, 
      "chainId": { "type": "user-provided" }, 
      "experimental": true, 
      "targetContract": { 
        "1": "0xEAD67175CDb9CBDeA5bDDC36015e52f4A954E3fD", 
        "name": "BitcoinOrdinals", 
        "description": "Ordinal Theory is a method for assigning unique identifiers to individual satoshis on the Bitcoin blockchain. This is done by assigning each satoshi a unique identifier based on the order in which it was mined. This identifier can be used to track the satoshi's history and ownership, and to transfer it to another party. Ordinal Theory can also be used to inscribe additional data to satoshis, such as a message, image, serial number, audio file, or document.",
        "fusion": false
      }, 
      "targetAsset": { 
        "name": "Loading...", 
        "image": "https://emblem.finance/ordinals.png"
      }
    }
  }
};

// Helper functions can be added here
